#!/usr/bin/env python3
"""Assembles the DSP equalizer routine and writes it as a C header for Rosalina.

usage: gen_header.py <path to makedsp1> <output header>

makedsp1 comes from Teakra (https://github.com/wwylele/teakra, build target `makedsp1`).
"""
import os, struct, subprocess, sys, tempfile
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_eq_asm as g

def main():
    makedsp1, out = sys.argv[1], sys.argv[2]
    a = g.gen()
    with tempfile.TemporaryDirectory() as tmp:
        src, dsp1 = os.path.join(tmp, 'eq.asm'), os.path.join(tmp, 'eq.dsp1')
        open(src, 'w').write(a.text())
        subprocess.check_call([makedsp1, src, dsp1])
        d = open(dsp1, 'rb').read()
    off, addr, size = struct.unpack_from('<3I', d, 0x120)
    assert addr == g.CODE_BASE
    words = struct.unpack_from('<%dH' % (size // 2), d, off)
    lines = ['/* Generated by tools/dsp_eq/gen_header.py - do not edit. */', '#pragma once', '',
             '#include <3ds/types.h>', '',
             '#define DSPEQ_CODE_BASE      0x%04X   // program memory word address the routine is placed at' % g.CODE_BASE,
             '#define DSPEQ_CODE_WORDS     %d' % len(words),
             '#define DSPEQ_HOOK_ADDR      0x%04X   // program word holding the operand of the hooked call' % 0x2FEC,
             '#define DSPEQ_ORIG_TARGET    0x%04X   // original call target (the routine we wrap)' % g.ORIG_CALL_TARGET,
             '#define DSPEQ_DATA_BASE      0x%04X   // data memory word address of the parameter block' % g.EQ,
             '#define DSPEQ_MAGIC          0x%04X' % g.MAGIC,
             '', '// DSP firmware words at DSPEQ_HOOK_ADDR - 8 .. DSPEQ_HOOK_ADDR that identify the supported firmware',
             'static const u16 dspEqHookFingerprint[9] = { 0x5F20, 0x00A0, 0x5EC4, 0x5E19, 0xC140, 0x5E18, 0xC000, 0x41C0, 0x%04X };' % g.ORIG_CALL_TARGET,
             '', 'static const u16 dspEqCode[DSPEQ_CODE_WORDS] = {']
    for i in range(0, len(words), 8):
        lines.append('    ' + ', '.join('0x%04X' % w for w in words[i:i + 8]) + ',')
    lines.append('};')
    open(out, 'w').write('\n'.join(lines) + '\n')
    print('wrote', out, len(words), 'words')

main()
