#!/usr/bin/env python3
"""Assembles the DSP equalizer routine and writes it as a C header for Rosalina.

usage: gen_header.py <path to makedsp1> <output header>

makedsp1 comes from Teakra (https://github.com/wwylele/teakra, build target `makedsp1`).
"""
import os, struct, subprocess, sys, tempfile
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_eq_asm as g

def main():
    makedsp1, out = sys.argv[1], sys.argv[2]
    a = g.gen(); a.resolve()
    with tempfile.TemporaryDirectory() as tmp:
        src, dsp1 = os.path.join(tmp, 'eq.asm'), os.path.join(tmp, 'eq.dsp1')
        open(src, 'w').write(a.text())
        subprocess.check_call([makedsp1, src, dsp1])
        d = open(dsp1, 'rb').read()
    off, addr, size = struct.unpack_from('<3I', d, 0x120)
    assert addr == g.CODE_BASE
    words = struct.unpack_from('<%dH' % (size // 2), d, off)
    lines = ['/* Generated by tools/dsp_eq/gen_header.py - do not edit. */', '#pragma once', '',
             '#include <3ds/types.h>', '',
             '#define DSPEQ_CODE_BASE      0x%04X   // program memory word address the routine is placed at' % g.CODE_BASE,
             '#define DSPEQ_CODE_WORDS     %d' % len(words),
             '#define DSPEQ_HOOK_A_NEW     0x%04X   // ENTRY_A: replaces the operand of the call to the plain copy routine' % a.labels['ENTRY_A'],
             '#define DSPEQ_HOOK_B_NEW     0x%04X   // ENTRY_B: same for the soft clipping routine' % a.labels['ENTRY_B'],
             '#define DSPEQ_ENTRY_A_OPERAND %d      // index in dspEqCode of the operands that must hold the ORIGINAL call targets' % (a.labels['ENTRY_A'] - g.CODE_BASE + 1),
             '#define DSPEQ_ENTRY_B_OPERAND %d' % (a.labels['ENTRY_B'] - g.CODE_BASE + 1),
             '#define DSPEQ_SCAN_FIRST     0x2000   // program memory range searched for the call sequence',
             '#define DSPEQ_SCAN_LAST      0x8000',
             '#define DSPEQ_DATA_BASE      0x%04X   // data memory word address of the parameter block' % g.EQ,
             '#define DSPEQ_MAGIC          0x%04X' % g.MAGIC,
             '#define DSPEQ_DIAG_CALLS     0x%04X   // word offsets (from DSPEQ_DATA_BASE) of the routine\'s diagnostic counters' % (g.DIAG_CALLS - g.EQ),
             '#define DSPEQ_DIAG_R4        0x%04X' % (g.DIAG_R4 - g.EQ),
             '#define DSPEQ_DIAG_A         0x%04X' % (g.DIAG_A - g.EQ),
             '#define DSPEQ_DIAG_B         0x%04X' % (g.DIAG_B - g.EQ),
             '#define DSPEQ_DIAG_IDX0      0x%04X' % (g.DIAG_IDX0 - g.EQ),
             '#define DSPEQ_DIAG_CF        0x%04X' % (g.DIAG_CF - g.EQ),
             '#define DSPEQ_DIAG_ST        0x%04X' % (g.DIAG_ST - g.EQ),
             '#define DSPEQ_DIAG_MOD       0x%04X' % (g.DIAG_MOD - g.EQ),
             '#define DSPEQ_DIAG_T         0x%04X' % (g.DIAG_T - g.EQ),
             '#define DSPEQ_DIAG_IDX1      0x%04X' % (g.DIAG_IDX1 - g.EQ),
             '', '// The audio output code of every supported firmware version contains this call sequence (0xFFFF = any value).',
             '// Word 8 is the target of the call to the plain copy routine, word 14 the target of the soft clipping call;',
             '// word 12 is the (version specific) address of the clipping parameters.',
             '#define DSPEQ_PATTERN_WORDS  16',
             '#define DSPEQ_PATTERN_ANY    0xFFFF',
             '#define DSPEQ_PATTERN_A      8',
             '#define DSPEQ_PATTERN_B      14',
             'static const u16 dspEqPattern[DSPEQ_PATTERN_WORDS] = { 0x5F20, 0x00A0, 0x5EC4, 0x5E19, 0xC140, 0x5E18, 0xC000, 0x41C0, 0xFFFF, 0x5050, 0x5B24, 0x5E18, 0xFFFF, 0x41C0, 0xFFFF, 0xD4B8 };',
             '', 'static const u16 dspEqCode[DSPEQ_CODE_WORDS] = {']
    for i in range(0, len(words), 8):
        lines.append('    ' + ', '.join('0x%04X' % w for w in words[i:i + 8]) + ',')
    lines.append('};')
    open(out, 'w').write('\n'.join(lines) + '\n')
    print('wrote', out, len(words), 'words')

main()
