#!/usr/bin/env python3
"""Assembles the DSP equalizer routine and writes it as a C header for Rosalina.

usage: gen_header.py <path to makedsp1> <output header>

makedsp1 comes from Teakra (https://github.com/wwylele/teakra, build target `makedsp1`).
"""
import os, struct, subprocess, sys, tempfile
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_eq_asm as g

def main():
    makedsp1, out = sys.argv[1], sys.argv[2]
    a = g.gen(); a.resolve()
    with tempfile.TemporaryDirectory() as tmp:
        src, dsp1 = os.path.join(tmp, 'eq.asm'), os.path.join(tmp, 'eq.dsp1')
        open(src, 'w').write(a.text())
        subprocess.check_call([makedsp1, src, dsp1])
        d = open(dsp1, 'rb').read()
    off, addr, size = struct.unpack_from('<3I', d, 0x120)
    assert addr == g.CODE_BASE
    words = struct.unpack_from('<%dH' % (size // 2), d, off)
    lines = ['/* Generated by tools/dsp_eq/gen_header.py - do not edit. */', '#pragma once', '',
             '#include <3ds/types.h>', '',
             '#define DSPEQ_CODE_BASE      0x%04X   // program memory word address the routine is placed at' % g.CODE_BASE,
             '#define DSPEQ_CODE_WORDS     %d' % len(words),
             '#define DSPEQ_HOOK_A_ADDR    0x%04X   // program word holding the operand of the hooked call (plain copy path)' % g.HOOK_A[0],
             '#define DSPEQ_HOOK_A_ORIG    0x%04X   // its original value (call target)' % g.HOOK_A[1],
             '#define DSPEQ_HOOK_A_NEW     0x%04X   // ENTRY_A' % a.labels['ENTRY_A'],
             '#define DSPEQ_HOOK_B_ADDR    0x%04X   // same for the soft clipping path' % g.HOOK_B[0],
             '#define DSPEQ_HOOK_B_ORIG    0x%04X' % g.HOOK_B[1],
             '#define DSPEQ_HOOK_B_NEW     0x%04X   // ENTRY_B' % a.labels['ENTRY_B'],
             '#define DSPEQ_FINGERPRINT_ADDR 0x2FE4 // first program word of the firmware fingerprint',
             '#define DSPEQ_DATA_BASE      0x%04X   // data memory word address of the parameter block' % g.EQ,
             '#define DSPEQ_MAGIC          0x%04X' % g.MAGIC,
             '#define DSPEQ_DIAG_CALLS     0x%04X   // word offsets (from DSPEQ_DATA_BASE) of the routine\'s diagnostic counters' % (g.DIAG_CALLS - g.EQ),
             '#define DSPEQ_DIAG_R4        0x%04X' % (g.DIAG_R4 - g.EQ),
             '#define DSPEQ_DIAG_A         0x%04X' % (g.DIAG_A - g.EQ),
             '#define DSPEQ_DIAG_B         0x%04X' % (g.DIAG_B - g.EQ),
             '#define DSPEQ_DIAG_IDX0      0x%04X' % (g.DIAG_IDX0 - g.EQ),
             '#define DSPEQ_DIAG_IDX1      0x%04X' % (g.DIAG_IDX1 - g.EQ),
             '', '// DSP firmware words at DSPEQ_FINGERPRINT_ADDR (the code around the two hooked calls) that identify the supported firmware',
             'static const u16 dspEqFingerprint[16] = { 0x5F20, 0x00A0, 0x5EC4, 0x5E19, 0xC140, 0x5E18, 0xC000, 0x41C0, 0x%04X, 0x5050, 0x5B24, 0x5E18, 0x3C30, 0x41C0, 0x%04X, 0xD4B8 };' % (g.HOOK_A[1], g.HOOK_B[1]),
             '', 'static const u16 dspEqCode[DSPEQ_CODE_WORDS] = {']
    for i in range(0, len(words), 8):
        lines.append('    ' + ', '.join('0x%04X' % w for w in words[i:i + 8]) + ',')
    lines.append('};')
    open(out, 'w').write('\n'.join(lines) + '\n')
    print('wrote', out, len(words), 'words')

main()
